Update solidity version to 8 and add github workflow
CoMakery/comakery-security-token pull request #29
Opened 2021-07-12 19:41 UTC by voyager-gold

2021-07-13 01:27 UTC, aquabu requested changes

2021-07-13 01:27 UTC, aquabu commented on contracts/RestrictedToken.sol
>      contractAdminCount = contractAdminCount.sub(1);
With Solidity 8.x SafeMath is now deprecated and should be removed to reduce gas costs. Documentation is here in the release notes "Checked Arithmetic":
https://blog.soliditylang.org/2020/12/16/solidity-v0.8.0-release-announcement/

And here is some OpenZeppelin related discussion:
https://www.gitmemory.com/issue/OpenZeppelin/openzeppelin-contracts/2465/757455677

2021-07-13 01:27 UTC, aquabu commented on contracts/RestrictedToken.sol
> +  bytes32 private constant _contractAdmins = DEFAULT_ADMIN_ROLE;
These used to be an array and so they were lower cased. Since these are now a constant identifier these constatns should probably be renamed to `CONTRACT_ADMIN_ROLE`, `TRANSFER_ADMIN_ROLE` etc.

2021-07-13 01:48 UTC, voyager-gold commented on contracts/RestrictedToken.sol
>      contractAdminCount = contractAdminCount.sub(1);
Removed SafeMath

2021-07-13 04:52 UTC, aquabu commented on contracts/RestrictedToken.sol
> +  bytes32 private constant TRANSFER_ADMIN_ROLE = keccak256("TRANSFER_ADMINS");
keccak256("TRANSFER_ADMINS") these probably should be singular
`keccak256("TRANSFER_ADMIN")`

2021-07-13 04:52 UTC, aquabu commented on contracts/RestrictedToken.sol
> +  bytes32 private constant CONTRACT_ADMIN_ROLE = DEFAULT_ADMIN_ROLE;
Where is the value of `DEFAULT_ADMIN_ROLE` defined?

2021-07-13 11:20 UTC, voyager-gold commented on contracts/RestrictedToken.sol
> +  bytes32 private constant CONTRACT_ADMIN_ROLE = DEFAULT_ADMIN_ROLE;
@openzeppelin/contracts/access/AccessControl.sol

2021-07-14 22:14 UTC, aquabu approved these changes

2021-07-14 22:14 UTC, merged