Denis d
CoMakery/comakery-security-token pull request #49
Opened 2021-11-23 20:40 UTC by Denis-Davidoff

SCD-4 Remove folder migrations (files removed by folder maybe not).
SCD-8 Complete, need check and verify, maybe write more tests for different situations

2021-11-23 20:45 UTC, Denis-Davidoff commented
I confused the name of the task in the committee
feat: SCD-7 (not 8) + test + deploy config

2021-11-24 00:25 UTC, aquabu requested changes

2021-11-24 00:25 UTC, aquabu commented on contracts/Dividends.sol
> +    mapping(uint256 => mapping(address => mapping(address => uint256))) fundersTokensGet; // snapshotID => funderAddress => token => getAmount;
The naming for `fundersTokensGet` could be clearer. Should this be `claimedTokens`

2021-11-24 00:25 UTC, aquabu commented on contracts/Dividends.sol
> +        require(paymentToken.balanceOf(msg.sender) >= amount, "SENDER HAVE NOT TOKENS");
Should be "SENDER DOES NOT HAVE TOKENS"

2021-11-24 00:25 UTC, aquabu commented on contracts/Dividends.sol
> +        require( _token != address(0), "WRONG TOKEN ADDRESS");
Maybe "BAD TOKEN ADDRESS"

2021-11-24 00:25 UTC, aquabu commented on contracts/Dividends.sol
> +        if ( tokensFunded[snapshotId][_token] > 0 ) {
I think the default value of `tokensFunded[snapshotId][_token]` always starts as `0` and not undefined. Also SafeMath isn't required for simple math operations like addition as of Solidity 0.8.0.

So you don't need the conditional statement or the SafeMath `add()` here and can just use:
 `tokensFunded[snapshotId][_token] += amount`

2021-11-24 00:25 UTC, aquabu commented on contracts/Dividends.sol
> +    function fundedAt(address _token, uint256 snapshotId) public view returns (uint256) {
Instead of `fundedAt()`, I think this should be called `fundsAt()`

2021-11-24 00:25 UTC, aquabu commented on contracts/Dividends.sol
> +        if ( fundersTokensGet[snapshotId][_token][msg.sender] > 0 ) {
Same comment as above. The default value is 0 so the conditional is not needed and this can just be:
fundersTokensGet[snapshotId][_token][msg.sender] += leftToReceive;

2021-11-24 00:25 UTC, aquabu commented on contracts/Dividends.sol
> +        uint256 seqTokenBalance = restrictedToken.balanceOfAt(msg.sender, snapshotId);
`secTokenBalance` instead of `seqTokenBalance`?

2021-11-24 00:25 UTC, aquabu commented on contracts/Dividends.sol
> +        require(seqTokenBalance > 0, "SECURITY TOKEN BALANCE IS NULL");
"SECURITY TOKEN BALANCE IS 0"

Is it better to raise an error here so it doesn't use any gas or is it better to just return without updating anything?

2021-11-24 00:25 UTC, aquabu commented
@Denis-Davidoff I think this looks like a good approach. I left a number of comments.
@voyager-gold can you review as well?

2021-11-24 00:39 UTC, aquabu commented on contracts/Dividends.sol
> +    }
I think we need more view functions for checking token holder balance types at different snapshots including:

```
totalAwardedBalanceAt(address token, address receiver, uint256 snapshotId)

claimedBalanceAt(address token, address receiver, uint256 snapshotId)

unclaimedBalanceAt(address token, address receiver, uint256 snapshotId)
```

2021-11-24 02:11 UTC, voyager-gold commented on contracts/Dividends.sol
> +    using SafeMath for uint256;
Nice catch. I agree with @aquabu

2021-11-24 02:17 UTC, voyager-gold commented on contracts/Dividends.sol
> +    event ClaimEvent (
Yes, it makes more sense to use past tense

2021-11-24 02:24 UTC, voyager-gold commented on test/js/snapshot.test.js
> +describe("Shapshot", function (accounts) {
It has mixed indentations. 4 or 2 spaces.
2 spacing is popular in Javascript indentation.

2021-11-24 02:37 UTC, voyager-gold commented on deploy/02_dividends.js
> +
We need to keep same length of indentation.

2021-11-24 03:11 UTC, voyager-gold requested changes
Nice working. I put some comments.
@Denis-Davidoff can you please give me details of SCDs handled in this PR?

2021-11-24 03:11 UTC, voyager-gold commented on contracts/Dividends.sol
> +        require(seqTokenBalance > 0, "SECURITY TOKEN BALANCE IS NULL");
Personally, `require` seems to be a good solution

2021-11-24 03:11 UTC, voyager-gold commented on contracts/Dividends.sol
> +        if ( fundersTokensGet[snapshotId][_token][msg.sender] > 0 ) {
Agreed, we can save code this way.

2021-11-24 03:11 UTC, voyager-gold commented on contracts/Dividends.sol
> +        require( _token != address(0), "WRONG TOKEN ADDRESS");
Not having a clear understanding of the specs, is this function for specific snapshot id, instead of last snapshot?

2021-11-24 03:11 UTC, voyager-gold commented on contracts/Dividends.sol
> +        require(IERC20(_token).approve(address(this), leftToReceive), "CONTRACT OUT OF TOKENS");
I don't think `approve` is required here.

2021-11-24 03:19 UTC, voyager-gold commented on contracts/Dividends.sol
> +        require(seqTokenBalance > 0, "SECURITY TOKEN BALANCE IS NULL");
Personally, it seems to be a nice solution to return error

2021-11-24 03:20 UTC, voyager-gold commented on contracts/Dividends.sol
> +        if ( fundersTokensGet[snapshotId][_token][msg.sender] > 0 ) {
Agreed, we can save code this way.

2021-11-24 03:20 UTC, voyager-gold commented on contracts/Dividends.sol
> +        if ( tokensFunded[snapshotId][_token] > 0 ) {
Nice catch

2021-11-24 13:32 UTC, Denis-Davidoff commented on contracts/Dividends.sol
> +        require(IERC20(_token).approve(address(this), leftToReceive), "CONTRACT OUT OF TOKENS");
Yes, it's not required, i can remove it.

2021-11-24 13:37 UTC, Denis-Davidoff commented on deploy/01_restricted_swap.js
> +  let res = await deploy('RestrictedSwap', {
I'm using it for debug, remove in fixes, all comments and not used variables.

2021-11-24 13:51 UTC, Denis-Davidoff commented on contracts/Dividends.sol
> +        if ( fundersTokensGet[snapshotId][_token][msg.sender] > 0 ) {
Agreed, condition required only with SafeMath. I removed SafeMath.

2021-11-24 14:02 UTC, Denis-Davidoff commented on contracts/Dividends.sol
> +        restrictedToken = RestrictedToken(_restrictedToken);
This is an open question, it should be discussed

2021-12-01 01:29 UTC, voyager-gold requested changes
@Denis-Davidoff can you please add natspec formatted comments to all variables and functions?
@aquabu
- Can you please give me an access to https://comakery-upside.atlassian.net/browse/SCD-7?
- How about making `Dividends` inherit from `RestrictedToken` and removing `Dividends.restrictedToken`?

2021-12-01 01:29 UTC, voyager-gold commented on contracts/Dividends.sol
> +    return tokensFunded[snapshotId][token] * share / 1000;
Isn't 1000 offset?

2021-12-01 06:19 UTC, aquabu commented on contracts/Dividends.sol
> +    restrictedToken = RestrictedToken(_restrictedToken);
Yes, it may be better to just use IERC20 if we aren't using other functions.

2021-12-01 06:21 UTC, aquabu commented on contracts/Dividends.sol
> +    return tokensFunded[snapshotId][token] * share / 1000;
@voyager-gold I think this may be to add precision in rounding. @Denis-Davidoff could you add parentheses here to make the order very obvious and also a comment about the intent.

2021-12-01 06:23 UTC, aquabu commented on contracts/Dividends.sol
> +    uint256 share = secTokenBalance * 1000 / totalSupply;
please add specs showing what happens with rounding. For example, what would happen if I was distributing:
* 1 token to 2 recipients
* 3 tokens to 2 recipients
* 9 tokens to 5 recipients
* 11 tokens to 5 recipients

2021-12-01 10:38 UTC, voyager-gold commented
@Denis-Davidoff As Noah said, we need more view functions for checking token holder balance types at different snapshots including:

```
totalAwardedBalanceAt(address token, address receiver, uint256 snapshotId)
claimedBalanceAt(address token, address receiver, uint256 snapshotId)
unclaimedBalanceAt(address token, address receiver, uint256 snapshotId)
```

Also @aquabu  How about making `Dividends` inherit from `RestrictedToken` and removing `Dividends.restrictedToken`?

2021-12-01 16:37 UTC, Denis-Davidoff commented on contracts/Dividends.sol
> +    uint256 share = secTokenBalance * 1000 / totalSupply;
I'm added precission from Restricted Token decimals thats allow maximal accuracy for low values.

2021-12-01 16:37 UTC, Denis-Davidoff commented
> @Denis-Davidoff As Noah said, we need more view functions for checking token holder balance types at different snapshots including:
> 
> ```
> totalAwardedBalanceAt(address token, address receiver, uint256 snapshotId)
> claimedBalanceAt(address token, address receiver, uint256 snapshotId)
> unclaimedBalanceAt(address token, address receiver, uint256 snapshotId)
> ```
> 
> Also @aquabu How about making `Dividends` inherit from `RestrictedToken` and removing `Dividends.restrictedToken`?

2021-12-01 16:37 UTC, closed without merging

2021-12-01 17:46 UTC, aquabu commented
@Denis-Davidoff I think we solved the contract size limitation issue.

It may be better to keep the contracts separate for a different reason though. We may want to be able to modularly deploy this code to attach to existing tokens. Would this code also work for ERC20?

Yes, we should add:
```
totalAwardedBalanceAt(address token, address receiver, uint256 snapshotId)
claimedBalanceAt(address token, address receiver, uint256 snapshotId)
unclaimedBalanceAt(address token, address receiver, uint256 snapshotId)
```

2021-12-01 18:02 UTC, Denis-Davidoff commented on contracts/Dividends.sol
> +    uint256 share = secTokenBalance * 1000 / totalSupply;
I'm add tests for its.

There you can see something like this:
Investor 1 has 5000 tokens. (25%)
Investor 2 has 5000 tokens. (25%)
TotalSupply - 20000 tokens.

1 token -> 0,0
3 tokens -> 0,0
5 tokens -> 1,1
9 tokens -> 2,2,
11 tokens -> 2,2
12 tokens -> 3,3
19 tokens -> 4,4
20 tokens -> 5,5