Security audit fixes
CoMakery/comakery-security-token pull request #51
Opened 2021-12-03 19:12 UTC by Denis-Davidoff

2021-12-06 06:11 UTC, aquabu requested changes

2021-12-06 09:46 UTC, Denis-Davidoff commented on contracts/RestrictedSwap.sol
> +  modifier onlyValidSwap(uint256 swapNumber_) {
I think that we use `_` on beginning for private methods and variables and `_` on ending for extended names.

2021-12-06 22:57 UTC, aquabu commented on contracts/RestrictedSwap.sol
> +  modifier onlyValidSwap(uint256 swapNumber_) {
ok that works

2021-12-06 22:57 UTC, aquabu approved these changes

2021-12-20 08:01 UTC, aquabu approved these changes

2021-12-20 08:01 UTC, merged